// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAuthorizedPublisherReducer from "../add_authorized_publisher_reducer";
import BootstrapAuthReducer from "../bootstrap_auth_reducer";
import ImportComponentsReducer from "../import_components_reducer";
import ImportHardpointCompatibilityReducer from "../import_hardpoint_compatibility_reducer";
import ImportInventoryContainersReducer from "../import_inventory_containers_reducer";
import ImportManufacturersReducer from "../import_manufacturers_reducer";
import ImportShipCargoReducer from "../import_ship_cargo_reducer";
import ImportShipDefaultsReducer from "../import_ship_defaults_reducer";
import ImportShipHardpointsReducer from "../import_ship_hardpoints_reducer";
import ImportShipsReducer from "../import_ships_reducer";
import PostCoordinationMessageReducer from "../post_coordination_message_reducer";
import PruneChangelogReducer from "../prune_changelog_reducer";
import PruneCoordinationMessagesReducer from "../prune_coordination_messages_reducer";
import PruneFormulaChangelogReducer from "../prune_formula_changelog_reducer";
import SetDataVersionReducer from "../set_data_version_reducer";
import UpdateCoordinationStateReducer from "../update_coordination_state_reducer";
import UpdateMessageStatusReducer from "../update_message_status_reducer";
import UpdateSkillVersionReducer from "../update_skill_version_reducer";
import UpdateSyncCursorReducer from "../update_sync_cursor_reducer";
import UpsertFormulaReducer from "../upsert_formula_reducer";

export type AddAuthorizedPublisherParams = __Infer<typeof AddAuthorizedPublisherReducer>;
export type BootstrapAuthParams = __Infer<typeof BootstrapAuthReducer>;
export type ImportComponentsParams = __Infer<typeof ImportComponentsReducer>;
export type ImportHardpointCompatibilityParams = __Infer<typeof ImportHardpointCompatibilityReducer>;
export type ImportInventoryContainersParams = __Infer<typeof ImportInventoryContainersReducer>;
export type ImportManufacturersParams = __Infer<typeof ImportManufacturersReducer>;
export type ImportShipCargoParams = __Infer<typeof ImportShipCargoReducer>;
export type ImportShipDefaultsParams = __Infer<typeof ImportShipDefaultsReducer>;
export type ImportShipHardpointsParams = __Infer<typeof ImportShipHardpointsReducer>;
export type ImportShipsParams = __Infer<typeof ImportShipsReducer>;
export type PostCoordinationMessageParams = __Infer<typeof PostCoordinationMessageReducer>;
export type PruneChangelogParams = __Infer<typeof PruneChangelogReducer>;
export type PruneCoordinationMessagesParams = __Infer<typeof PruneCoordinationMessagesReducer>;
export type PruneFormulaChangelogParams = __Infer<typeof PruneFormulaChangelogReducer>;
export type SetDataVersionParams = __Infer<typeof SetDataVersionReducer>;
export type UpdateCoordinationStateParams = __Infer<typeof UpdateCoordinationStateReducer>;
export type UpdateMessageStatusParams = __Infer<typeof UpdateMessageStatusReducer>;
export type UpdateSkillVersionParams = __Infer<typeof UpdateSkillVersionReducer>;
export type UpdateSyncCursorParams = __Infer<typeof UpdateSyncCursorReducer>;
export type UpsertFormulaParams = __Infer<typeof UpsertFormulaReducer>;

