// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  appId: __t.string().primaryKey().name("app_id"),
  appName: __t.string().name("app_name"),
  lastSyncedHash: __t.string().name("last_synced_hash"),
  lastSyncedSeq: __t.u64().name("last_synced_seq"),
  updatedAt: __t.u64().name("updated_at"),
});
