// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  hash: __t.string(),
  gameVersion: __t.string().name("game_version"),
  updatedAt: __t.u64().name("updated_at"),
  versionSeq: __t.u64().name("version_seq"),
  counts: __t.string(),
  changeCount: __t.u64().name("change_count"),
});
