// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  formulaId: __t.string().name("formula_id"),
  version: __t.u32(),
  previousExpression: __t.string().name("previous_expression"),
  newExpression: __t.string().name("new_expression"),
  reason: __t.string(),
  updatedBy: __t.string().name("updated_by"),
  updatedAt: __t.u64().name("updated_at"),
});
