// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  domain: __t.string(),
  description: __t.string(),
  expression: __t.string(),
  variables: __t.string(),
  implementation: __t.string(),
  version: __t.u32(),
  verifiedInGameVersion: __t.string().name("verified_in_game_version"),
  verifiedAt: __t.u64().name("verified_at"),
  notes: __t.string(),
  updatedBy: __t.string().name("updated_by"),
  updatedAt: __t.u64().name("updated_at"),
});
