// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  subType: __t.string().name("sub_type"),
  size: __t.string(),
  ref: __t.string(),
  path: __t.string(),
  category: __t.string(),
  icon: __t.string(),
  invisible: __t.u8(),
  entityDensityClass: __t.string().name("entity_density_class"),
  vehicleRole: __t.string().name("vehicle_role"),
  vehicleCareer: __t.string().name("vehicle_career"),
  modification: __t.string(),
  manufacturer: __t.string(),
  crewSize: __t.u16().name("crew_size"),
  boundingBoxX: __t.f64().name("bounding_box_x"),
  boundingBoxY: __t.f64().name("bounding_box_y"),
  boundingBoxZ: __t.f64().name("bounding_box_z"),
  hullDamageNormalization: __t.f64().name("hull_damage_normalization"),
  componentPenetrationMultiplier: __t.f64().name("component_penetration_multiplier"),
  fusePenetrationMultiplier: __t.f64().name("fuse_penetration_multiplier"),
  baseWaitTimeMinutes: __t.f64().name("base_wait_time_minutes"),
  mandatoryWaitTimeMinutes: __t.f64().name("mandatory_wait_time_minutes"),
  baseExpeditingFee: __t.u32().name("base_expediting_fee"),
  dogfightEnabled: __t.u8().name("dogfight_enabled"),
  isGravlevVehicle: __t.u8().name("is_gravlev_vehicle"),
  cargoDeckLoaded: __t.u8().name("cargo_deck_loaded"),
  cargoRequiresDocking: __t.u8().name("cargo_requires_docking"),
  health: __t.f64(),
  damageCap: __t.f64().name("damage_cap"),
  isRepairable: __t.u8().name("is_repairable"),
  isSalvagable: __t.u8().name("is_salvagable"),
  damageResistances: __t.string().name("damage_resistances"),
  weaponPoolSize: __t.u32().name("weapon_pool_size"),
  ammoLoadMultiplier: __t.f64().name("ammo_load_multiplier"),
  powerPoolConfig: __t.string().name("power_pool_config"),
  cargoCapacityScu: __t.u32().name("cargo_capacity_scu"),
});
