// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  shipId: __t.string().name("ship_id"),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  minSize: __t.u8().name("min_size"),
  maxSize: __t.u8().name("max_size"),
  types: __t.string(),
  categories: __t.string(),
});
