// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AppSyncCursors = __t.object("AppSyncCursors", {
  appId: __t.string(),
  appName: __t.string(),
  lastSyncedHash: __t.string(),
  lastSyncedSeq: __t.u64(),
  updatedAt: __t.u64(),
});
export type AppSyncCursors = __Infer<typeof AppSyncCursors>;

export const AuthorizedPublishers = __t.object("AuthorizedPublishers", {
  identity: __t.string(),
  label: __t.string(),
  addedAt: __t.u64(),
});
export type AuthorizedPublishers = __Infer<typeof AuthorizedPublishers>;

export const Components = __t.object("Components", {
  entityClassName: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  type: __t.string(),
  subType: __t.string(),
  size: __t.u8(),
  grade: __t.string(),
  manufacturerCode: __t.string(),
  manufacturerName: __t.string(),
  ref: __t.string(),
  path: __t.string(),
  category: __t.string(),
  icon: __t.string(),
  invisible: __t.u8(),
  entityDensityClass: __t.string(),
  inheritParentManufacturer: __t.u8(),
  displayThumbnail: __t.string(),
  damageCap: __t.f64(),
  isSalvagable: __t.u8(),
  isRepairable: __t.u8(),
  detachFromItemPortOnDeath: __t.u8(),
  isResourceNetworked: __t.u8(),
  defaultPriority: __t.u8(),
  resource: __t.string(),
  resourceConsumption: __t.string(),
  resourceGeneration: __t.string(),
  emSignature: __t.f64(),
  irSignature: __t.f64(),
  maxLifetimeHours: __t.f64(),
  initialAgeRatio: __t.f64(),
  distortionMaximum: __t.f64(),
  distortionDecayRate: __t.f64(),
  distortionDecayDelay: __t.f64(),
  distortionRecoveryRatio: __t.f64(),
  typeParams: __t.string(),
  powerDrawResolved: __t.f64(),
  powerGenerationResolved: __t.f64(),
  coolingRateResolved: __t.f64(),
  coolantDrawResolved: __t.f64(),
  shieldRegenResolved: __t.f64(),
  powerSegments: __t.u32(),
  powerBands: __t.string(),
  minimumConsumptionFraction: __t.f64(),
});
export type Components = __Infer<typeof Components>;

export const CoordinationMessages = __t.object("CoordinationMessages", {
  id: __t.string(),
  sourceApp: __t.string(),
  messageType: __t.string(),
  severity: __t.string(),
  title: __t.string(),
  body: __t.string(),
  parentId: __t.option(__t.string()),
  status: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type CoordinationMessages = __Infer<typeof CoordinationMessages>;

export const CoordinationState = __t.object("CoordinationState", {
  id: __t.string(),
  phase: __t.string(),
  agreedItems: __t.string(),
  pendingItems: __t.string(),
  updatedAt: __t.u64(),
});
export type CoordinationState = __Infer<typeof CoordinationState>;

export const DataChangelog = __t.object("DataChangelog", {
  id: __t.string(),
  versionSeq: __t.u64(),
  tableName: __t.string(),
  operation: __t.string(),
  recordKey: __t.string(),
  recordData: __t.option(__t.string()),
});
export type DataChangelog = __Infer<typeof DataChangelog>;

export const DataVersion = __t.object("DataVersion", {
  id: __t.u32(),
  hash: __t.string(),
  gameVersion: __t.string(),
  updatedAt: __t.u64(),
  versionSeq: __t.u64(),
  counts: __t.string(),
  changeCount: __t.u64(),
});
export type DataVersion = __Infer<typeof DataVersion>;

export const FormulaChangelog = __t.object("FormulaChangelog", {
  id: __t.string(),
  formulaId: __t.string(),
  version: __t.u32(),
  previousExpression: __t.string(),
  newExpression: __t.string(),
  reason: __t.string(),
  updatedBy: __t.string(),
  updatedAt: __t.u64(),
});
export type FormulaChangelog = __Infer<typeof FormulaChangelog>;

export const Formulas = __t.object("Formulas", {
  id: __t.string(),
  name: __t.string(),
  domain: __t.string(),
  description: __t.string(),
  expression: __t.string(),
  variables: __t.string(),
  implementation: __t.string(),
  version: __t.u32(),
  verifiedInGameVersion: __t.string(),
  verifiedAt: __t.u64(),
  notes: __t.string(),
  updatedBy: __t.string(),
  updatedAt: __t.u64(),
});
export type Formulas = __Infer<typeof Formulas>;

export const HardpointCompatibility = __t.object("HardpointCompatibility", {
  id: __t.string(),
  hardpointId: __t.string(),
  componentId: __t.string(),
});
export type HardpointCompatibility = __Infer<typeof HardpointCompatibility>;

export const InventoryContainers = __t.object("InventoryContainers", {
  id: __t.string(),
  containerType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  scu: __t.u32(),
});
export type InventoryContainers = __Infer<typeof InventoryContainers>;

export const Manufacturers = __t.object("Manufacturers", {
  ref: __t.string(),
  code: __t.string(),
  name: __t.string(),
  description: __t.string(),
  logo: __t.string(),
  logoFullColor: __t.string(),
  logoSimplifiedWhite: __t.string(),
  dashboardCanvasConfig: __t.string(),
  ecnCode: __t.string(),
});
export type Manufacturers = __Infer<typeof Manufacturers>;

export const ShipCargo = __t.object("ShipCargo", {
  id: __t.string(),
  shipId: __t.string(),
  containerId: __t.string(),
  containerType: __t.string(),
});
export type ShipCargo = __Infer<typeof ShipCargo>;

export const ShipDefaults = __t.object("ShipDefaults", {
  id: __t.string(),
  shipId: __t.string(),
  hardpointName: __t.string(),
  defaultComponentId: __t.string(),
});
export type ShipDefaults = __Infer<typeof ShipDefaults>;

export const ShipHardpoints = __t.object("ShipHardpoints", {
  id: __t.string(),
  shipId: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  minSize: __t.u8(),
  maxSize: __t.u8(),
  types: __t.string(),
  categories: __t.string(),
});
export type ShipHardpoints = __Infer<typeof ShipHardpoints>;

export const Ships = __t.object("Ships", {
  id: __t.string(),
  displayName: __t.string(),
  subType: __t.string(),
  size: __t.string(),
  ref: __t.string(),
  path: __t.string(),
  category: __t.string(),
  icon: __t.string(),
  invisible: __t.u8(),
  entityDensityClass: __t.string(),
  vehicleRole: __t.string(),
  vehicleCareer: __t.string(),
  modification: __t.string(),
  manufacturer: __t.string(),
  crewSize: __t.u16(),
  boundingBoxX: __t.f64(),
  boundingBoxY: __t.f64(),
  boundingBoxZ: __t.f64(),
  hullDamageNormalization: __t.f64(),
  componentPenetrationMultiplier: __t.f64(),
  fusePenetrationMultiplier: __t.f64(),
  baseWaitTimeMinutes: __t.f64(),
  mandatoryWaitTimeMinutes: __t.f64(),
  baseExpeditingFee: __t.u32(),
  dogfightEnabled: __t.u8(),
  isGravlevVehicle: __t.u8(),
  cargoDeckLoaded: __t.u8(),
  cargoRequiresDocking: __t.u8(),
  health: __t.f64(),
  damageCap: __t.f64(),
  isRepairable: __t.u8(),
  isSalvagable: __t.u8(),
  damageResistances: __t.string(),
  weaponPoolSize: __t.u32(),
  ammoLoadMultiplier: __t.f64(),
  powerPoolConfig: __t.string(),
  cargoCapacityScu: __t.u32(),
});
export type Ships = __Infer<typeof Ships>;

export const SkillVersions = __t.object("SkillVersions", {
  skillName: __t.string(),
  contentHash: __t.string(),
  updatedAt: __t.u64(),
});
export type SkillVersions = __Infer<typeof SkillVersions>;

