// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.string(),
  domain: __t.string(),
  description: __t.string(),
  expression: __t.string(),
  variables: __t.string(),
  implementation: __t.string(),
  version: __t.u32(),
  verifiedInGameVersion: __t.string(),
  verifiedAt: __t.u64(),
  notes: __t.string(),
  updatedBy: __t.string(),
  reason: __t.string(),
};
